name: WallPay
options:
  bundleIdPrefix: com.wallpay
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  
settings:
  base:
    SWIFT_VERSION: "5.9"
    GENERATE_INFOPLIST_FILE: YES
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    
targets:
  WallPay:
    type: application
    platform: iOS
    sources:
      - path: WallPay
        type: group
    settings:
      base:
        INFOPLIST_FILE: WallPay/Info.plist
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_LSApplicationQueriesSchemes: "shortcuts"
        PRODUCT_BUNDLE_IDENTIFIER: com.wallpay.app
        PRODUCT_NAME: WallPay
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        ENABLE_PREVIEWS: YES
